;; Generated by protoc-gen-clojure 0.7.0 (f3a8449) from acme/greeter/greeter.proto. Do not edit.
;;
;; The FileDescriptorProto below is embedded verbatim; protobuf-java resolves
;; its edition features at load time, so this file needs no regeneration when
;; a new edition ships.
(ns acme.greeter.greeter
  (:require [clj-protobuf.codec :as codec]
            [clj-protobuf.runtime :as rt]
            [clj-grpc.service :as rts]))

(def ^:private descriptor-b64
  "ChphY21lL2dyZWV0ZXIvZ3JlZXRlci5wcm90bxIMYWNtZS5ncmVldGVyIkAKBEl0ZW0SEAoDc2t1GAEgASgJUgNza3USEAoDcXR5GAIgASgFUgNxdHkSFAoFcHJpY2UYAyABKAFSBXByaWNlIqIBCgdQYXlsb2FkEg4KAmlkGAEgASgJUgJpZBIUCgV0aXRsZRgCIAEoCVIFdGl0bGUSEgoEYm9keRgDIAEoCVIEYm9keRIdCgpjcmVhdGVkX2F0GAQgASgDUgljcmVhdGVkQXQSFAoFc2NvcmUYBSABKAFSBXNjb3JlEigKBWl0ZW1zGAYgAygLMhIuYWNtZS5ncmVldGVyLkl0ZW1SBWl0ZW1zIqoBCgxIZWxsb1JlcXVlc3QSEgoEbmFtZRgBIAEoCVIEbmFtZRIhCgxyZXBlYXRfY291bnQYAiABKAVSC3JlcGVhdENvdW50EjIKCGdyZWV0aW5nGAMgASgOMhYuYWNtZS5ncmVldGVyLkdyZWV0aW5nUghncmVldGluZxIvCgdwYXlsb2FkGAQgASgLMhUuYWNtZS5ncmVldGVyLlBheWxvYWRSB3BheWxvYWQiVwoKSGVsbG9SZXBseRIYCgdtZXNzYWdlGAEgASgJUgdtZXNzYWdlEi8KB3BheWxvYWQYAiABKAsyFS5hY21lLmdyZWV0ZXIuUGF5bG9hZFIHcGF5bG9hZCpMCghHcmVldGluZxIYChRHUkVFVElOR19VTlNQRUNJRklFRBAAEhIKDkdSRUVUSU5HX0hFTExPEAESEgoOR1JFRVRJTkdfSE9XRFkQAjKeAgoHR3JlZXRlchJACghTYXlIZWxsbxIaLmFjbWUuZ3JlZXRlci5IZWxsb1JlcXVlc3QaGC5hY21lLmdyZWV0ZXIuSGVsbG9SZXBseRJGCgxTYXlIZWxsb01hbnkSGi5hY21lLmdyZWV0ZXIuSGVsbG9SZXF1ZXN0GhguYWNtZS5ncmVldGVyLkhlbGxvUmVwbHkwARJHCg1Db2xsZWN0SGVsbG9zEhouYWNtZS5ncmVldGVyLkhlbGxvUmVxdWVzdBoYLmFjbWUuZ3JlZXRlci5IZWxsb1JlcGx5KAESQAoEQ2hhdBIaLmFjbWUuZ3JlZXRlci5IZWxsb1JlcXVlc3QaGC5hY21lLmdyZWV0ZXIuSGVsbG9SZXBseSgBMAFCEgoQY29tLmFjbWUuZ3JlZXRlcmIIZWRpdGlvbnNw6Qc=")

(def file-descriptor
  (rt/file-descriptor descriptor-b64
                      []))

;; ---------------------------------------------------------------
;; messages
(declare proto->Item--slot-map proto->Payload--slot-map)
;;
;; The shape is known at codegen time, so the representation is too:
;; a defrecord per type, its FieldDescriptors resolved once into
;; vars, and straight-line ->proto/proto-> built on them. nil means
;; absent, which is how a record (all keys always present) maps onto
;; protobuf explicit presence.

(defrecord Item [sku qty price])
(def Item-prototype (rt/message file-descriptor "Item" "com.acme.greeter.Item"))
(def ^:private Item--sku (rt/field Item-prototype "sku"))
(def ^:private Item--qty (rt/field Item-prototype "qty"))
(def ^:private Item--price (rt/field Item-prototype "price"))
(defn Item->proto
  "Clojure -> protobuf. Takes the Item record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Item->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Item-prototype)]
     (codec/set-field! b Item--sku (:sku m) opts)
     (codec/set-field! b Item--qty (:qty m) opts)
     (codec/set-field! b Item--price (:price m) opts)
     (.build b))))
(defn proto->Item
  "protobuf -> a Item record. Absent fields are nil."
  ([msg] (proto->Item msg nil))
  ([^com.google.protobuf.Message msg opts]
   (if (and (nil? opts) (rt/compiled-message? msg))
     (->Item
      (rt/slot msg 0)
      (rt/slot msg 1)
      (rt/slot msg 2)
      )
     (->Item
      (codec/get-field msg Item--sku opts)
      (codec/get-field msg Item--qty opts)
      (codec/get-field msg Item--price opts)
      ))))
(defn- proto->Item--slot-map
  "Item as a plain map, read from the compiled arm's slots:
  the same values, minus the keys the codec's read leaves out."
  [msg]
  (let [sku--v (rt/slot msg 0)
        qty--v (rt/slot msg 1)
        price--v (rt/slot msg 2)]
    (if (and (some? sku--v) (some? qty--v) (some? price--v))
      {:sku sku--v
       :qty qty--v
       :price price--v}
      (persistent!
       (cond-> (transient {})
         (some? sku--v) (assoc! :sku sku--v)
         (some? qty--v) (assoc! :qty qty--v)
         (some? price--v) (assoc! :price price--v)
         )))))

(defrecord Payload [id title body created-at score items])
(def Payload-prototype (rt/message file-descriptor "Payload" "com.acme.greeter.Payload"))
(def ^:private Payload--id (rt/field Payload-prototype "id"))
(def ^:private Payload--title (rt/field Payload-prototype "title"))
(def ^:private Payload--body (rt/field Payload-prototype "body"))
(def ^:private Payload--created-at (rt/field Payload-prototype "created_at"))
(def ^:private Payload--score (rt/field Payload-prototype "score"))
(def ^:private Payload--items (rt/field Payload-prototype "items"))
(defn Payload->proto
  "Clojure -> protobuf. Takes the Payload record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (Payload->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message Payload-prototype)]
     (codec/set-field! b Payload--id (:id m) opts)
     (codec/set-field! b Payload--title (:title m) opts)
     (codec/set-field! b Payload--body (:body m) opts)
     (codec/set-field! b Payload--created-at (:created-at m) opts)
     (codec/set-field! b Payload--score (:score m) opts)
     (codec/set-field! b Payload--items (:items m) opts)
     (.build b))))
(defn proto->Payload
  "protobuf -> a Payload record. Absent fields are nil."
  ([msg] (proto->Payload msg nil))
  ([^com.google.protobuf.Message msg opts]
   (if (and (nil? opts) (rt/compiled-message? msg))
     (->Payload
      (rt/slot msg 0)
      (rt/slot msg 1)
      (rt/slot msg 2)
      (rt/slot msg 3)
      (rt/slot msg 4)
      (let [^java.util.List l (rt/slot msg 5)] (when (and l (pos? (.size l))) (persistent! (reduce (fn [acc v] (conj! acc (proto->Item--slot-map v))) (transient []) l))))
      )
     (->Payload
      (codec/get-field msg Payload--id opts)
      (codec/get-field msg Payload--title opts)
      (codec/get-field msg Payload--body opts)
      (codec/get-field msg Payload--created-at opts)
      (codec/get-field msg Payload--score opts)
      (codec/get-field msg Payload--items opts)
      ))))
(defn- proto->Payload--slot-map
  "Payload as a plain map, read from the compiled arm's slots:
  the same values, minus the keys the codec's read leaves out."
  [msg]
  (let [id--v (rt/slot msg 0)
        title--v (rt/slot msg 1)
        body--v (rt/slot msg 2)
        created-at--v (rt/slot msg 3)
        score--v (rt/slot msg 4)
        items--v (let [^java.util.List l (rt/slot msg 5)] (when (and l (pos? (.size l))) (persistent! (reduce (fn [acc v] (conj! acc (proto->Item--slot-map v))) (transient []) l))))]
    (if (and (some? id--v) (some? title--v) (some? body--v) (some? created-at--v) (some? score--v) (some? items--v))
      {:id id--v
       :title title--v
       :body body--v
       :created-at created-at--v
       :score score--v
       :items items--v}
      (persistent!
       (cond-> (transient {})
         (some? id--v) (assoc! :id id--v)
         (some? title--v) (assoc! :title title--v)
         (some? body--v) (assoc! :body body--v)
         (some? created-at--v) (assoc! :created-at created-at--v)
         (some? score--v) (assoc! :score score--v)
         (some? items--v) (assoc! :items items--v)
         )))))

(defrecord HelloRequest [name repeat-count greeting payload])
(def HelloRequest-prototype (rt/message file-descriptor "HelloRequest" "com.acme.greeter.HelloRequest"))
(def ^:private HelloRequest--name (rt/field HelloRequest-prototype "name"))
(def ^:private HelloRequest--repeat-count (rt/field HelloRequest-prototype "repeat_count"))
(def ^:private HelloRequest--greeting (rt/field HelloRequest-prototype "greeting"))
(def ^:private HelloRequest--payload (rt/field HelloRequest-prototype "payload"))
(defn HelloRequest->proto
  "Clojure -> protobuf. Takes the HelloRequest record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (HelloRequest->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message HelloRequest-prototype)]
     (codec/set-field! b HelloRequest--name (:name m) opts)
     (codec/set-field! b HelloRequest--repeat-count (:repeat-count m) opts)
     (codec/set-field! b HelloRequest--greeting (:greeting m) opts)
     (codec/set-field! b HelloRequest--payload (:payload m) opts)
     (.build b))))
(defn proto->HelloRequest
  "protobuf -> a HelloRequest record. Absent fields are nil."
  ([msg] (proto->HelloRequest msg nil))
  ([^com.google.protobuf.Message msg opts]
   (if (and (nil? opts) (rt/compiled-message? msg))
     (->HelloRequest
      (rt/slot msg 0)
      (rt/slot msg 1)
      (when-some [v (rt/slot msg 2)] (case v 0 :GREETING_UNSPECIFIED 1 :GREETING_HELLO 2 :GREETING_HOWDY (codec/get-field msg HelloRequest--greeting nil)))
      (when-some [v (rt/slot msg 3)] (proto->Payload--slot-map v))
      )
     (->HelloRequest
      (codec/get-field msg HelloRequest--name opts)
      (codec/get-field msg HelloRequest--repeat-count opts)
      (codec/get-field msg HelloRequest--greeting opts)
      (codec/get-field msg HelloRequest--payload opts)
      ))))

(defrecord HelloReply [message payload])
(def HelloReply-prototype (rt/message file-descriptor "HelloReply" "com.acme.greeter.HelloReply"))
(def ^:private HelloReply--message (rt/field HelloReply-prototype "message"))
(def ^:private HelloReply--payload (rt/field HelloReply-prototype "payload"))
(defn HelloReply->proto
  "Clojure -> protobuf. Takes the HelloReply record or any map
  with the same keys — records and plain maps are interchangeable."
  ([m] (HelloReply->proto m nil))
  ([m opts]
   (let [b (.newBuilderForType ^com.google.protobuf.Message HelloReply-prototype)]
     (codec/set-field! b HelloReply--message (:message m) opts)
     (codec/set-field! b HelloReply--payload (:payload m) opts)
     (.build b))))
(defn proto->HelloReply
  "protobuf -> a HelloReply record. Absent fields are nil."
  ([msg] (proto->HelloReply msg nil))
  ([^com.google.protobuf.Message msg opts]
   (if (and (nil? opts) (rt/compiled-message? msg))
     (->HelloReply
      (rt/slot msg 0)
      (when-some [v (rt/slot msg 1)] (proto->Payload--slot-map v))
      )
     (->HelloReply
      (codec/get-field msg HelloReply--message opts)
      (codec/get-field msg HelloReply--payload opts)
      ))))

;; services — pass the service value to your server, the methods to a client
(def Greeter (rts/service file-descriptor "Greeter"))
(def greeter-methods (rts/methods-map Greeter))
