(ns clj-grpc.runtime.service
  "DEPRECATED alias for clj-grpc.service.

  Code generated by protoc-gen-clojure <= 0.3.x requires this namespace; from
  0.4.0 the default is clj-grpc.service. Removed at 1.0."
  {:deprecated "0.1.0"}
  (:require [clj-grpc.service :as service]))

(def ^{:deprecated "0.1.0"} service service/service)
(def ^{:deprecated "0.1.0"} methods-map service/methods-map)
